---
title: "Graphs for Blackrock"
output: github_document
---

This code takes the outputs from code run on the WRDS cloud, typically data.tables, and creates the necessary graphs and visualizations.

```{r setup, include =FALSE}
rm(list=ls())
knitr::opts_knit$set(results='hide')
knitr::opts_chunk$set(fig.width=8, fig.height=6) 


library(ggplot2)
library(data.table)
library(zoo)
```

## Load and polish data

```{r load data}
#br <- readRDS(file = 'output/sin_frac_by_type_sep23.rds')

br <- fread(file = 'output/blackrock.csv', header = TRUE, stringsAsFactors = FALSE)[order(yq)]

br$date <- as.Date( as.yearqtr(br$yq), frac = 1 )

```

```{r plot total assets}
plot <- ggplot(data= br, aes(x=date, y=tot.value))+
    geom_line()+
    ggtitle("Value of holdings in sample over time")+
    ylab("Wigthed fraction to Sin") + xlab('Quarter')
plot
```

```{r plot number of observations}
plot <- ggplot(data= br, aes(x=date, y=num.obs))+
    geom_line()+
    ggtitle("Number of holdings observations in sample over time")+
    ylab("Wigthed fraction to Sin") + xlab('Quarter')
plot
```
## Who holds sin stocks
```{r plot sin}
plot <- ggplot(data= br, aes(x=date,y=sin.frac.unwei))+
    geom_line()+
    ggtitle("Fraction of portfolio in Sin stocks (unweighted)")+
    ylab("Wigthed fraction to Sin") + xlab('Quarter')
plot
```
```{r plot sin unweighted}
plot <- ggplot(data= br, aes(x=date,y=sin.frac))+
    geom_line()+
    labs(color = "Investor Type") +
    ggtitle("Fraction of portfolio in Sin stocks (weighted)")+
    ylab("Fraction to Sin") + xlab("Quarter")
plot
```
## Who holds fossil stocks
```{r plot fossil}
plot <- ggplot(data= br, aes(x=date,y=fossil.frac.unwei))+
    geom_line()+
    labs(color = "Investor Type") +
    ggtitle("Fraction of portfolio in Fossil stocks by investor type (unweighted)")+
    ylab("Wigthed fraction to Fossil")+ xlab('Quarter')
plot
```
```{r plot fossil unweighted}
plot <- ggplot(data= br, aes(x=date,y=fossil.frac))+
    geom_line()+
    labs(color = "Investor Type") +
    ggtitle("Fraction of portfolio in Fossil stocks (weighted)")+
    ylab("Fraction to Fossil")+ xlab('Quarter')
plot
```